---
title: "A Fresh Start"
date: 2018-08-08

title: Blog-First Draft
author: Yi Cai
email: yi.cai@emory.edu
description: > # this means to ignore newlines until "baseurl:"
A great place to know more about me, my passion, my past experiences, and my coding works.

# social links

github_username:  caiyyy

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
---
